import { v4 as uuid } from "uuid";
import { formatDate } from "../utils/authUtils";

/**
 * Posts can be added here.
 * You can add default posts of your wish with different attributes
 * */

export const posts = [
  //news 1
  {
    _id: "post11",
    title:'ICSE Class 10 results: Hargun Kaur Matharu from Pune is all-India topper',
    url:'https://res.cloudinary.com/chanchal12/image/upload/v1658154274/bd3abc1e-0601-11ed-9fcc-33d54995b06e_1658084234000_hxsdim.jpg',
    content:"All-India Indian Certificate of Secondary Education (ICSE) topper Hargun Kaur Matharu, from St Mary’s School, Pune, secured 99 #result #10th",
    likes: {
      likeCount: 0,
      likedBy: [],
      dislikedBy: [],
    },
    profileImage:"https://res.cloudinary.com/chanchal12/image/upload/v1657479753/chanchal_j0tmjv.jpg",
    firstName: "chanchal",
		lastName: "panpaliya",
    username: "chanchalpanpaliya@gmail.com",
    userId:"qwertyuiop11",
    //
    tagName : [],
    gethashtag : ['result','10th'],
    postTopic:"News",
    postType:"EVENT",
    postPolicy : "public",
    eventLocation : "The Orchid Hotel, Baner ,Pune",
    eventDate : "2022-07-23T16:43:34+05:30",
    //
    createdAt: "2022-05-15T16:43:34+05:30",
    updatedAt: "2022-05-15T16:43:34+05:30",
    comments: [
      {
        _id: uuid(),
        username: "sneha roy",
        text: "Congratulations! We're so very proud of you!",
        votes: {
          upvotedBy: [],
          downvotedBy: [],
        },
      },
      {
        _id: uuid(),
        username: "ankita shingh",
        text: "Your hard work and perseverance have paid off. Congratulations!",
        votes: {
          upvotedBy: [],
          downvotedBy: [],
        },
      },
      {
        _id: uuid(),
        username: "anika mohan",
        text: "Congratulations on your well-deserved success! You're an inspiration!",
        votes: {
          upvotedBy: [],
          downvotedBy: [],
        },
      },
    ],
  },
  //news 2
  {
    _id: "post12",
    title:'Shiv Sena will rejoice if Uddhav and Shinde reunite: Sanjay Raut',
    url:'https://res.cloudinary.com/chanchal12/image/upload/v1658160696/raut-2_o831kr.jpg',
    content:"“I won’t say it will be a new dawn for the party or will boost the Sena’s image, but yes it will certainly be a happier moment for the entire Shiv Sena,” Raut told The Indian Express, a day after party leader and Marathi actor Deepali Sayeed expressed the possibility of Uddhav and Shinde coming together. #shivsena #jaimaharashtra",
    likes: {
      likeCount: 0,
      likedBy: [],
      dislikedBy: [],
    },
    profileImage:"https://res.cloudinary.com/chanchal12/image/upload/v1657479753/chanchal_j0tmjv.jpg",
    firstName: "chanchal",
		lastName: "panpaliya",
    username: "chanchalpanpaliya@gmail.com",
    userId:"qwertyuiop11",
    //
    tagName : [],
    gethashtag : ['shivsena','jaimaharashtra'],
    postTopic:"Politics",
    postType:"EVENT",
    postPolicy : "public",
    eventLocation : "The Orchid Hotel, Baner ,Pune",
    eventDate : "2022-07-23T16:43:34+05:30",
    //
    createdAt: "2022-05-17T16:43:34+05:30",
    updatedAt: "2022-05-17T16:43:34+05:30",
    comments: [],
  },
  {
    _id: "post13",
    title:"Pune Ritika Khatnani crowned Miss Supranational Asia 2022!",
    url:'https://res.cloudinary.com/chanchal12/image/upload/v1658161824/Master_fcs3ok.jpg',
    content:"The diva who gave a stellar performance throughout the pageant was ecstatic with her win, and hold on, she did not win just one but two awards. Ritika who aspires to be a Superstar one day was also awarded the Miss Photogenic title.",
    likes: {
      likeCount: 0,
      likedBy: [],
      dislikedBy: [],
    },
    profileImage:"https://res.cloudinary.com/chanchal12/image/upload/v1657479753/chanchal_j0tmjv.jpg",
    firstName: "chanchal",
		lastName: "panpaliya",
    username: "chanchalpanpaliya@gmail.com",
    userId:"qwertyuiop11",
       //
       tagName : [],
       gethashtag : [],
       postType:"EVENT",
       postPolicy : "public",
       postTopic:"Fashion",
       eventLocation : "The Orchid Hotel, Baner ,Pune",
       eventDate : "2022-07-23T16:43:34+05:30",
       //
    createdAt: "2022-07-15T16:43:34+05:30",
    updatedAt: "2022-07-15T16:43:34+05:30",
    comments: [
      {
        _id: uuid(),
        username: "adarshbalika",
        text: " At a very young age, the diva stepped into the world of pageants . congratulations ritika!!!",
        votes: {
          upvotedBy: [],
          downvotedBy: [],
        },
      },
      {
        _id: uuid(),
        username: "krupa28",
        text: "Wow!",
        votes: {
          upvotedBy: [],
          downvotedBy: [],
        },
      },
      {
        _id: uuid(),
        username: "krupa28",
        text: "our queen...",
        votes: {
          upvotedBy: [],
          downvotedBy: [],
        },
      },
    ],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: "post14",
    title:'Shivangi Joshi said, "Khatron Ke Khiladi 12 is going to be my first ever reality show"',
    url:'https://res.cloudinary.com/chanchal12/image/upload/v1660670163/maxresdefault_rpbj0d.jpg',
    content:
     "Wow dream entry on bike 🔥🔥 So excited to see her in KKK12 Only excited for #shernishivi #ShivangiJoshi  #Shivangians  #KhatronKeKhiladi12 #KKK12 ",    
    likes: {
      likeCount: 0,
      likedBy: [],
      dislikedBy: [],
    },
    profileImage:"https://res.cloudinary.com/chanchal12/image/upload/v1657479753/chanchal_j0tmjv.jpg",
    firstName: "chanchal",
		lastName: "panpaliya",
    username: "chanchalpanpaliya@gmail.com",
    userId:"qwertyuiop11",
     //
     tagName : [],
     gethashtag : ['ShivangiJoshi','Shivangians','KhatronKeKhiladi12','KKK12'],
     postType:"EVENT",
     postPolicy : "public",
     postTopic:"TV",
     eventLocation : "The Orchid Hotel, Baner ,Pune",
     eventDate : "2022-07-23T16:43:34+05:30",
     //
    createdAt: "2022-01-19T16:43:34+05:30",
    updatedAt: "2022-01-19T16:43:34+05:30",
    comments: [
      {
        _id: uuid(),
        username: "adarshbalika",
        text: "My whole heart with shivi pie she is pure soul",
        votes: {
          upvotedBy: [],
          downvotedBy: [],
        },
      },
      {
        _id: uuid(),
        username: "krupa28",
        text: "Shivangi sherni hai 🦁🦁🦁🦁🦁🦁🦁",
        votes: {
          upvotedBy: [],
          downvotedBy: [],
        },
      },
    ],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  }, 
  //
  {
    _id: "post16",
    title:"Pune University Students To Get Free Guidance About GRE, TOEFL, IELTS For Higher Studies Abroad",
    url:'https://res.cloudinary.com/chanchal12/image/upload/v1658163228/Sppu-pune-University-_geb8s1.jpg',
    content:"A Memorandum of Understanding (MoU) has recently been signed between the Savitribai Phule Pune University’s International Center, under which Indian students will now be given free guidance to study abroad. Under this, language courses like GRE, TOEFL, IELTS will be taught free of cost.",    
    likes: {
      likeCount: 0,
      likedBy: [],
      dislikedBy: [],
    },
    profileImage:"https://res.cloudinary.com/chanchal12/image/upload/v1657479753/chanchal_j0tmjv.jpg",
    firstName: "chanchal",
		lastName: "panpaliya",
    username: "chanchalpanpaliya@gmail.com",
    userId:"qwertyuiop11",
     //
     tagName : [],
     gethashtag : [],
     postType:"EVENT",
     postPolicy : "public",
     postTopic:"Study",
     eventLocation : "The Orchid Hotel, Baner ,Pune",
     eventDate : "2022-07-23T16:43:34+05:30",
     //
    createdAt: "2022-03-19T16:43:34+05:30",
    updatedAt: "2022-03-19T16:43:34+05:30",
    comments: [
      {
        _id: uuid(),
        username: "adarshbalika",
        text: "great initiative",
        votes: {
          upvotedBy: [],
          downvotedBy: [],
        },
      }
    ],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  //Event
  {
    _id: "post17event1",
    title:"Gaurav Kapoor Live",
    url:'https://res.cloudinary.com/chanchal12/image/upload/v1658163633/media-desktop-gaurav-kapoor-live-0-2022-2-5-t-9-58-55_bl7gxc.jpg',
    content:"Comedy Shows | Hindi | 1hr , ₹499 each",    
    likes: {
      likeCount: 0,
      likedBy: [],
      dislikedBy: [],
    },
    profileImage:"https://res.cloudinary.com/chanchal12/image/upload/v1657479753/chanchal_j0tmjv.jpg",
    firstName: "chanchal",
		lastName: "panpaliya",
    username: "chanchalpanpaliya@gmail.com",
    userId:"qwertyuiop11",
     //
     tagName : [],
     gethashtag : [],
     postType:"EVENT",
     postPolicy : "public",
     postTopic:"Other",
     eventLocation : "The Orchid Hotel, Baner ,Pune ",
     eventDate : "2022-07-23T16:43:34+05:30",
     //
    createdAt: "2022-03-19T16:43:34+05:30",
    updatedAt: "2022-03-19T16:43:34+05:30",
    comments: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: "post17event2",
    title:"Kunal Kamra Live",
    url:'https://res.cloudinary.com/chanchal12/image/upload/v1658171659/media-desktop-kunal-kamra-live-0-2022-7-4-t-14-23-29_y2a120.jpg',
    content:"Comedy Shows | English, Hindi | 18yrs + | 1hr 15mins , ₹999 each",    
    likes: {
      likeCount: 0,
      likedBy: [],
      dislikedBy: [],
    },
    profileImage:"https://res.cloudinary.com/chanchal12/image/upload/v1657479753/chanchal_j0tmjv.jpg",
    firstName: "chanchal",
		lastName: "panpaliya",
    username: "chanchalpanpaliya@gmail.com",
    userId:"qwertyuiop11",
     //
     tagName : [],
     gethashtag : [],
     postType:"EVENT",
     postPolicy : "public",
     postTopic:"Other",
     eventLocation : "Seasons Mall, hadapsar ,Pune ",
     eventDate : "2022-10-06T19:43:34+05:30",
     //
    createdAt: "2022-03-19T16:43:34+05:30",
    updatedAt: "2022-03-19T16:43:34+05:30",
    comments: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: "post17event3",
    title:"Nucleya Live Pune ( Waters Bar & Kitchen)",
    url:'https://res.cloudinary.com/chanchal12/image/upload/v1658171916/media-desktop-nucleya-live-pune-waters-bar-kitchen-0-2022-7-10-t-5-4-15_mfaxdw.jpg',
    content:"Music Shows | 5hrs, ₹699 each",    
    likes: {
      likeCount: 0,
      likedBy: [],
      dislikedBy: [],
    },
    profileImage:"https://res.cloudinary.com/chanchal12/image/upload/v1657479753/chanchal_j0tmjv.jpg",
    firstName: "chanchal",
		lastName: "panpaliya",
    username: "chanchalpanpaliya@gmail.com",
    userId:"qwertyuiop11",
     //
     tagName : [],
     gethashtag : [],
     postType:"EVENT",
     postPolicy : "public",
     postTopic:"Other",
     eventLocation : "FC Road ,Pune ",
     eventDate : "2022-08-14T19:43:34+05:30",
     //
    createdAt: "2022-07-12T16:43:34+05:30",
    updatedAt: "2022-07-12T16:43:34+05:30",
    comments: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: "post17event4",
    title:"Supermoon Ft. Imran Khan - Pune",
    url:'https://res.cloudinary.com/chanchal12/image/upload/v1658172285/media-desktop-supermoon-ft-imran-khan-pune-0-2022-7-14-t-9-50-41_gbfkwn.jpg',
    content:"Hip Hop, Pop, Punjabi | Punjabi | 21yrs + | 3hrs ₹1000 each",    
    likes: {
      likeCount: 0,
      likedBy: [],
      dislikedBy: [],
    },
    profileImage:"https://res.cloudinary.com/chanchal12/image/upload/v1657479753/chanchal_j0tmjv.jpg",
    firstName: "chanchal",
		lastName: "panpaliya",
    username: "chanchalpanpaliya@gmail.com",
    userId:"qwertyuiop11",
     //
     tagName : [],
     gethashtag : [],
     postType:"EVENT",
     postPolicy : "public",
     postTopic:"Other",
     eventLocation : "CityOne Mall ,Pune ",
     eventDate : "2022-07-31T19:43:34+05:30",
     //
    createdAt: "2022-07-12T16:43:34+05:30",
    updatedAt: "2022-07-12T16:43:34+05:30",
    comments: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: "post17event5",
    title:"SANAM live Pune ( Drome Arena @Mayfield Esate )",
    url:'https://res.cloudinary.com/chanchal12/image/upload/v1658172700/media-desktop-sanam-live-pune-drome-arena-mayfield-esate-0-2022-7-13-t-7-30-39_qjyzba.jpg',
    content:"Hip Hop, Pop, Punjabi | Punjabi | 21yrs + | 3hrs ₹1250 each Sanam is an Indian pop-rock band formed in 2010 and currently based in Mumbai, India. Known for its renditions of old classic Indian Bollywood songs as well as original music. The band SANAM consists of Sanam Puri, Samar Puri, Venky S or Venkat Subramaniyam and Keshav Dhanraj. SANAM has charmed 10 million+ fans on Youtube",    
    likes: {
      likeCount: 0,
      likedBy: [],
      dislikedBy: [],
    },
    profileImage:"https://res.cloudinary.com/chanchal12/image/upload/v1657479753/chanchal_j0tmjv.jpg",
    firstName: "chanchal",
		lastName: "panpaliya",
    username: "chanchalpanpaliya@gmail.com",
    userId:"qwertyuiop11",
     //
     tagName : [],
     gethashtag : [],
     postType:"EVENT",
     postPolicy : "public",
     postTopic:"Other",
     eventLocation : "CityOne Mall ,Pune ",
     eventDate : "2022-08-06T19:43:34+05:30",
     //
    createdAt: "2022-06-06T16:43:34+05:30",
    updatedAt: "2022-06-06T16:43:34+05:30",
    comments: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: "post17event6",
    title:"Paathshaala : Standup Comedy show by Vinay Tiwari",
    url:'https://res.cloudinary.com/chanchal12/image/upload/v1658173025/media-desktop-paathshaala-standup-comedy-show-by-vinay-tiwari-0-2022-7-4-t-14-22-12_iydvb1.jpg',
    content:"Comedy Shows | Hindi, English | 16yrs + | 1hr 30mins ₹125 Paathshaala is a Standup Comedy show featuring Vinay Tiwari. Come watch him Live in Pune as he takes you through his hilarious journey in his Standup Comedy Solo show! Opening spot by Akash Singh. Couple Discounts available!",    
    likes: {
      likeCount: 0,
      likedBy: [],
      dislikedBy: [],
    },
    profileImage:"https://res.cloudinary.com/dexubgbx0/image/upload/v1653736290/dan_o6nk9h.jpg",
    firstName: "Rahul",
		lastName: "Pant",
    username: "rahulpant@gmail.com",
    userId:"wertyui345678",
     //
     tagName : [],
     gethashtag : [],
     postType:"EVENT",
     postPolicy :"public",
     postTopic:"Other",
     eventLocation : "PVR, Pimpri ,Pune ",
     eventDate : "2022-07-28T19:43:34+05:30",
     //
    createdAt: "2022-06-02T16:43:34+05:30",
    updatedAt: "2022-06-02T16:43:34+05:30",
    comments: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: "post17event7",
    title:"Srinath Narayanan Teaches Chess",
    url:'https://res.cloudinary.com/chanchal12/image/upload/v1658173602/media-desktop-srinath-narayanan-teaches-chess-0-2022-1-25-t-11-17-48_xjrxif.jpg',
    content:"Books and Literature, Sports | English | All age groups | 3hrs 20mins ₹999 each",    
    likes: {
      likeCount: 0,
      likedBy: [],
      dislikedBy: [],
    },
    profileImage:"https://res.cloudinary.com/chanchal12/image/upload/v1658157890/Anime-Girl-Profile-Picture_u00vet.jpg",
    firstName: "Ankita",
		lastName: "Lokhande",
    username: "ankitaLokahde@12",
    userId:"mnbvcxzoiuytre",
     //
     tagName : [],
     gethashtag : [],
     postType:"EVENT",
     postPolicy :"public",
     postTopic:"Study",
     eventLocation : "Times Hall ,Shivaji nagar,Pune ",
     eventDate : "2022-07-25T19:43:34+05:30",
     //
    createdAt: "2022-07-02T16:43:34+05:30",
    updatedAt: "2022-06-02T16:43:34+05:30",
    comments: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  //
  {
    _id: "post21",
    title:'Avoid These Beauty Treatments This Summer',
    url:'https://res.cloudinary.com/chanchal12/image/upload/v1660670240/Hair-Transplant-Women1_pwru5g.jpg',
    content:
     "Hair transplant is a permanent hair replacement surgical treatment that allows treatment of male/female patterned baldness. It is usually a 6-8 hour long procedure done under local anaesthesia. ",    
     likes: {
      likeCount: 0,
      likedBy: [],
      dislikedBy: [],
    },
    profileImage:"https://res.cloudinary.com/chanchal12/image/upload/v1658157890/Anime-Girl-Profile-Picture_u00vet.jpg",
    firstName: "Ankita",
		lastName: "Lokhande",
		username: "ankitaLokahde@12",
    userId:"mnbvcxzoiuytre",
       //
       tagName : [],
       gethashtag : [],
       postType:"EVENT",
       postTopic:"Politics",
       postPolicy : "public",
       eventLocation : "The Orchid Hotel, Baner ,Pune",
       eventDate : "2022-07-23T16:43:34+05:30",
       //
    createdAt: "2022-05-15T16:43:34+05:30",
    updatedAt: "2022-05-15T16:43:34+05:30",
    comments: [
      {
        _id: uuid(),
        username: "adarshbalika",
        text: "Interesting",
        votes: {
          upvotedBy: [],
          downvotedBy: [],
        },
      },
      {
        _id: uuid(),
        username: "krupa28",
        text: "Wow!",
        votes: {
          upvotedBy: [],
          downvotedBy: [],
        },
      },
    ],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: "5555",
    title:'Makeup Tips To Apply Primer',
    url:'https://res.cloudinary.com/chanchal12/image/upload/v1660670051/decoded-makeup_OI_mzflfx.jpg',
    content:
      "Whether oil or water, your primer and foundation should share the same base; ",
    likes: {
      likeCount: 0,
      likedBy: [],
      dislikedBy: [],
    },
    profileImage:"https://res.cloudinary.com/chanchal12/image/upload/v1658157890/Anime-Girl-Profile-Picture_u00vet.jpg",
    firstName: "Ankita",
    lastName: "Lokhande",
    username: "ankitaLokahde@12",
    userId:"mnbvcxzoiuytre",
     //
     tagName : [],
     gethashtag : [],
     postType:"EVENT",
     postPolicy : "public",
     postTopic:"Other",
     eventLocation : "The Orchid Hotel, Baner ,Pune",
     eventDate : "2022-07-23T16:43:34+05:30",
     //
    createdAt: "2022-05-15T16:43:34+05:30",
    updatedAt: "2022-05-15T16:43:34+05:30",
    comments: [
      {
        _id: uuid(),
        username: "sneharoy",
        text: "Interesting",
        votes: {
          upvotedBy: [],
          downvotedBy: [],
        },
      },
      {
        _id: uuid(),
        username: "isha",
        text: "Wow!",
        votes: {
          upvotedBy: [],
          downvotedBy: [],
        },
      },
    ],
  },
  {
    _id: "6666",
    title:'HOW TO WEAR BROWN LIP LINER',
    url:'https://res.cloudinary.com/shrushti23/image/upload/v1655739103/78693107_10157776757264173_8467512149864873984_n_kcd03u.jpg',
    content:
      "Start by choosing your perfect shade of brown or nude lip liner. Our Color Sensational Shaping Lip Liners come in 21 awesome, long-lasting shades.Smile so your lips are stretched out and apply your liner, starting at the cupid's bow. Smiling ensures you cover your entire lip.Next, fill in the outer corners of your lips with the liner and blend with your fingertips. Do one section at a time.You can leave your lips lined and matte as a final look…or you can apply lipstick.",
    likes: {
      likeCount: 0,
      likedBy: [],
      dislikedBy: [],
    },
    firstName: "Ankita",
    lastName: "Lokhande",
    username: "ankitaLokahde@12",
    userId:"mnbvcxzoiuytre",
    profileImage:"https://res.cloudinary.com/chanchal12/image/upload/v1658157890/Anime-Girl-Profile-Picture_u00vet.jpg",
       //
       tagName : [],
       gethashtag : [],
       postType:"EVENT",
       postPolicy : "public",
       eventLocation : "The Orchid Hotel, Baner ,Pune",
       postTopic:"Other",
       eventDate : "2022-07-23T16:43:34+05:30",
       //
    createdAt: "2022-05-15T16:43:34+05:30",
    updatedAt: "2022-05-15T16:43:34+05:30",
    comments: [
      {
        _id: uuid(),
        username: "adarshbalika",
        text: "Interesting",
        votes: {
          upvotedBy: [],
          downvotedBy: [],
        },
      },
      {
        _id: uuid(),
        username: "krupa28",
        text: "Wow!",
        votes: {
          upvotedBy: [],
          downvotedBy: [],
        },
      },
    ],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: "post312198654321",
    title:'Shop Opening "Shubham Jewellers"',
    url:'https://res.cloudinary.com/chanchal12/image/upload/v1658203595/shubham-jewellers-katraj-pune-jewellery-showrooms-1lk9p2gwlg_ynvnw1.jpg',
    content:
      "Shop No 4 Pooja Complex, DattaNagar Road, Katraj, Pune - 411046, Opposite Reliance Fresh",
    likes: {
      likeCount: 0,
      likedBy: [],
      dislikedBy: [],
    },
    firstName: "Himanshi",
    lastName: "Raja",
    username: "himanshiraja@123",
    userId:"kjhgfdsauytr",
    profileImage:"https://res.cloudinary.com/dexubgbx0/image/upload/v1652872677/28102735662_5773509d11_b_zpjwv0.webp",
       //
       tagName : [],
       gethashtag : [],
       postType:"EVENT",
       postPolicy : "public",
       eventLocation : "The Orchid Hotel, Baner ,Pune",
       postTopic:"Other",
       eventDate : "2022-07-23T16:43:34+05:30",
       //
    createdAt: "2022-05-15T16:43:34+05:30",
    updatedAt: "2022-05-15T16:43:34+05:30",
    comments: [
      {
        _id: uuid(),
        username: "rahulpant@gmail.com",
        text: "Best of luck with your new business. I wish nothing but the growth and prosperity of your new business.",
        votes: {
          upvotedBy: [],
          downvotedBy: [],
        },
      },
      {
        _id: uuid(),
        username: "chanchalpanpaliya@gmail.com",
        text: "Congratulations on the grand opening of your new shop. Wishing your business never-ending success.",
        votes: {
          upvotedBy: [],
          downvotedBy: [],
        },
      },
      {
        _id: uuid(),
        username: "ankitalokhande1234",
        text: "all my best wishes to you for starting a new business. Best of luck.",
        votes: {
          upvotedBy: [],
          downvotedBy: [],
        },
      },
    ],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: "post3124",
    title:'Victory Day',
    url:'https://res.cloudinary.com/chanchal12/image/upload/v1658215213/Pune-win-isl_vmfsrr.jpg',
    content:"#victoryday",
    likes: {
      likeCount: 0,
      likedBy: [],
      dislikedBy: [],
    },
    firstName: "Aniket",
    lastName: "Sharma",
    username: "aniketsharma@123",
    userId:"sdasdffghjk234",
    profileImage:"https://res.cloudinary.com/chanchal12/image/upload/v1658215279/soccer-player-man-isolated-picture-id544358500_eyrqqt.jpg",
       //
       tagName : [],
       gethashtag : [],
       postType:"EVENT",
       postPolicy : "public",
       eventLocation : "The Orchid Hotel, Baner ,Pune",
       postTopic:"Other",
       eventDate : "2022-07-23T16:43:34+05:30",
       //
    createdAt: "2022-05-15T16:43:34+05:30",
    updatedAt: "2022-05-15T16:43:34+05:30",
    comments: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: "post3121",
    title:'Got married!!!',
    url:'https://res.cloudinary.com/chanchal12/image/upload/v1658205073/25-Samples-Of-Wedding-Announcement-Wording-Banner.jpg_tdi8qd.webp',
    content:
      "Got married!!! Ankita Lokhande . A hundred hearts would be too few to carry all my love for you",
    likes: {
      likeCount: 0,
      likedBy: [],
      dislikedBy: [],
    },
    firstName: "Aniket",
    lastName: "Sharma",
    username: "aniketsharma@123",
    userId:"sdasdffghjk234",
    profileImage:"https://res.cloudinary.com/chanchal12/image/upload/v1658215279/soccer-player-man-isolated-picture-id544358500_eyrqqt.jpg",
       //
       tagName : [
        {id: 'mnbvcxzoiuytre', username: 'ankitaLokahde@12'}
      ],
       gethashtag : [],
       postType:"EVENT",
       postPolicy : "private",
       eventLocation : "The Orchid Hotel, Baner ,Pune",
       postTopic:"Other",
       eventDate : "2022-07-23T16:43:34+05:30",
       //
    createdAt: "2021-05-15T16:43:34+05:30",
    updatedAt: "2021-05-15T16:43:34+05:30",
    comments: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: "post3122",
    title:'my chotu birthday',
    url:'https://res.cloudinary.com/chanchal12/image/upload/v1658215426/804ffed1720999bb77fcaa32abf17df3--mother-son-pictures-mother-son-photos-baby_wrhkiz.jpg',
    content:"Wishing my chotu a very very happy bday...may all your wishes come true and u live a long n happy life baccha.....😘",
    likes: {
      likeCount: 0,
      likedBy: [],
      dislikedBy: [],
    },
    firstName: "Aniket",
    lastName: "Sharma",
    username: "aniketsharma@123",
    userId:"sdasdffghjk234",
    profileImage:"https://res.cloudinary.com/chanchal12/image/upload/v1658215279/soccer-player-man-isolated-picture-id544358500_eyrqqt.jpg",
       //
       tagName : [],
       gethashtag : [],
       postType:"EVENT",
       postPolicy : "private",
       eventLocation : "The Orchid Hotel, Baner ,Pune",
       postTopic:"Other",
       eventDate : "2022-07-23T16:43:34+05:30",
       //
    createdAt: "2022-05-15T16:43:34+05:30",
    updatedAt: "2022-05-15T16:43:34+05:30",
    comments: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
];
